/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.ktlint)
}

val appVersion =
    providers
        .fileContents(layout.projectDirectory.file("src/main/kotlin/org/example/AppVersion.kt"))
        .asText
        .map { text ->
            text
                .lineSequence()
                .first { "APP_VERSION" in it }
                .substringAfter('"')
                .substringBefore('"')
        }.get()

version = appVersion

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    google()
}

dependencies {
    implementation(compose.desktop.currentOs)
    implementation(libs.compose.material3)
    implementation(libs.derby)
    implementation(libs.kotlinx.serialization.json)

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.snakeyaml)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

compose.desktop {
    application {
        mainClass = "org.example.AppKt"

        nativeDistributions {
            packageName = "PenaUtilityToolNext"
            packageVersion = appVersion
            modules("java.sql")
        }
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    systemProperty(
        "skiko.data.path",
        layout.buildDirectory
            .dir("skiko")
            .get()
            .asFile.absolutePath,
    )
}

tasks.withType<JavaExec>().configureEach {
    if (name == "run") {
        systemProperty("pena.app.dir", rootProject.projectDir.absolutePath)
        systemProperty("pena.development", "true")
    }
}
